BlogoBlog.App/Controllers/LoginController.cs
using BlogoBlog.App.Models.Login;
using BlogoBlog.Logic.Enums;
using BlogoBlog.Logic.Providers;
using BlogoBlog.Logic.Registration;
using BlogoBlog.Logic.Services;
using System.Web.Mvc;
using DryIoc;

namespace BlogoBlog.App.Controllers
{
    public class LoginController : BaseController
    {
        [HttpGet]
        public ActionResult Login()
        {
            var model = new LoginViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            var result = new RegistrationService().Login(model.Login, model.Password);
            if (result == ELoginResult.OK)
            {
                new CookieService(HttpContext.Request, HttpContext.Response).AddUserCookie(model.Login);
                return RedirectToAction("Index", "Home");
            }
            CreateErrorMessage(l10n.Translation.LoginErrorMessage);
            return View(model);
        }

        /// <summary>
        /// should be done by post TODO
        /// </summary>
        [HttpGet]
        public ActionResult Logout()
        {
            new CookieService(Request, Response).RemoveLoggedUserCookie();
            return RedirectToAction("Index", "Home");
        }
    }
}

BlogoBlog.App/Controllers/RegistrationController.cs
using BlogoBlog.App.Models.Registration;
using BlogoBlog.Logic.Enums;
using BlogoBlog.Logic.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogoBlog.App.Controllers
{
    public class RegistrationController : BaseController
    {
        [HttpGet]
        public ActionResult Register()
        {
            return View(new RegistrationViewModel());
        }

        [HttpPost]
        public ActionResult Register(RegistrationViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            
            if (model.Password != model.PasswordRepeated)
            {
                CreateErrorMessage(l10n.Translation.PasswordsMustBeEqual);
                return View(model);
            }

            var service = new RegistrationService();
            var result = service.Register(model.Email, model.Password, model.Username, model.IsBlogger);
            if (result != ERegistrationResponse.OK)
            {
                CreateErrorMessage(result.ToString());
                return View(model);
            }
            new CookieService(HttpContext.Request, HttpContext.Response).AddUserCookie(model.Username);
            Database.Db.Save();
            return RedirectToAction("Index", "Home");
        }
    }
}

BlogoBlog.App/Controllers/UserController.cs
using BlogoBlog.App.Models.User;
using BlogoBlog.Database;
using BlogoBlog.Logic.Enums;
using BlogoBlog.Logic.Providers;
using BlogoBlog.Logic.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogoBlog.App.Controllers
{
    public class UserController : BaseController
    {
        public ActionResult Index()
        {
            var user = GetLoggedUser();
            var model = new UserViewModel()
            {
                Email = user.Email,
                Username = user.Name,
                UserType = (EUserType)user.Type
            };
            return View(model);
        }
        [HttpGet]
        public ActionResult UpgradeType()
        {
            var user = GetLoggedUser();
            user.Type = (int)EUserType.Blogger;
            Db.Save();
            return RedirectToAction("Index");
        }
    }
}

BlogoBlog.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-image: url('../../Content/Images/background-img.jpg'); background-size: cover">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blogoblog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-header">
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        var loggedUserCookie = BlogoBlog.Logic.Services.CookieService.GetLoggedUserCookie(Request);
                        if (loggedUserCookie == null || string.IsNullOrEmpty(loggedUserCookie.Value))
                        {
                            <li>@Html.ActionLink(BlogoBlog.App.l10n.Translation.Registration, "Register", "Registration")</li>
                            <li>@Html.ActionLink(BlogoBlog.App.l10n.Translation.Login, "Login", "Login")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink(loggedUserCookie.Value, "Index", "User")</li>
                            <li>@Html.ActionLink(BlogoBlog.App.l10n.Translation.Logout, "Logout", "Login")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
        {
            <div class="alert-danger text-center navbar">
                @ViewBag.ErrorMessage
            </div>
        }
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>